/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["listProjects"];
        put?: never;
        /** Create project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /** Archive project */
        delete: operations["archiveProject"];
        options?: never;
        head?: never;
        /** Update project */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{project_id}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List project memberships */
        get: operations["listProjectMemberships"];
        put?: never;
        /** Create project membership */
        post: operations["createProjectMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/memberships/{membership_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke project membership */
        delete: operations["revokeProjectMembership"];
        options?: never;
        head?: never;
        /** Update project membership role */
        patch: operations["updateProjectMembership"];
        trace?: never;
    };
    "/projects/{project_id}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List meetings in project */
        get: operations["listProjectMeetings"];
        put?: never;
        /** Create meeting */
        post: operations["createMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/conversation-imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List conversation imports in project */
        get: operations["listProjectConversationImports"];
        put?: never;
        /** Create a manual conversation import */
        post: operations["createConversationImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversation-imports/{conversation_import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get conversation import */
        get: operations["getConversationImport"];
        put?: never;
        post?: never;
        /** Anonymize a conversation import and remove retained DM text */
        delete: operations["anonymizeConversationImport"];
        options?: never;
        head?: never;
        /** Update conversation import text, redaction, or consent metadata */
        patch: operations["updateConversationImport"];
        trace?: never;
    };
    "/conversation-imports/{conversation_import_id}/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan a conversation import before AI processing */
        post: operations["scanConversationImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversation-imports/{conversation_import_id}/generate-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate an AI summary draft from a scanned conversation import */
        post: operations["generateConversationSummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversation-summary-drafts/{conversation_summary_draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get conversation summary draft */
        get: operations["getConversationSummaryDraft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update conversation summary draft after human review */
        patch: operations["updateConversationSummaryDraft"];
        trace?: never;
    };
    "/conversation-summary-drafts/{conversation_summary_draft_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a conversation summary draft for downstream requirements and issue drafting */
        post: operations["approveConversationSummaryDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get meeting */
        get: operations["getMeeting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{meeting_id}/generate-minutes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate minutes from a meeting */
        post: operations["generateMinutes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/minutes/{minutes_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get minutes */
        get: operations["getMinutes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update minutes */
        patch: operations["updateMinutes"];
        trace?: never;
    };
    "/minutes/{minutes_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve minutes */
        post: operations["approveMinutes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/minutes/{minutes_id}/generate-requirement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate requirement from minutes */
        post: operations["generateRequirement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requirements/{requirement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get requirement */
        get: operations["getRequirement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update requirement */
        patch: operations["updateRequirement"];
        trace?: never;
    };
    "/requirements/{requirement_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve requirement */
        post: operations["approveRequirement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requirements/{requirement_id}/generate-issue-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate GitHub issue draft from requirement */
        post: operations["generateIssueDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requirements/{requirement_id}/generate-openapi-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate OpenAPI draft from requirement */
        post: operations["generateOpenApiDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issue-drafts/{issue_draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get issue draft */
        get: operations["getIssueDraft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update issue draft */
        patch: operations["updateIssueDraft"];
        trace?: never;
    };
    "/issue-drafts/{issue_draft_id}/publish-github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish approved issue draft to GitHub */
        post: operations["publishIssueDraftToGitHub"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issue-drafts/{issue_draft_id}/reconcile-github-publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile a GitHub Issue publish attempt by marker search */
        post: operations["reconcileGitHubIssuePublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issue-drafts/{issue_draft_id}/resolve-github-reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve a GitHub publish reconciliation blocker manually */
        post: operations["resolveGitHubIssueReconciliation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi-drafts/{openapi_draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get OpenAPI draft */
        get: operations["getOpenApiDraft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update OpenAPI draft */
        patch: operations["updateOpenApiDraft"];
        trace?: never;
    };
    "/openapi-drafts/{openapi_draft_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate OpenAPI draft */
        post: operations["validateOpenApiDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reviews */
        get: operations["listReviews"];
        put?: never;
        /** Create review */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}/resolve-action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark review action resolved */
        post: operations["resolveReviewAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}/accept-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark review blocker as accepted risk */
        post: operations["acceptReviewRisk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List project integrations */
        get: operations["listProjectIntegrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/integrations/github/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start GitHub connection */
        post: operations["startGitHubConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/integrations/github/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disconnect GitHub integration */
        post: operations["disconnectGitHubIntegration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete GitHub connection callback */
        post: operations["completeGitHubConnectionCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive GitHub App webhook */
        post: operations["receiveGitHubWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get generation or integration job */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/queue-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get read-only queue health */
        get: operations["getQueueHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit logs */
        get: operations["listProjectAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string;
            /** @enum {string} */
            status: "active" | "archived";
            github_repo?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProjectResponse: {
            data: components["schemas"]["Project"];
        };
        ProjectListResponse: {
            data: components["schemas"]["Project"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        CreateProjectRequest: {
            name: string;
            description?: string;
            github_repo?: string;
        };
        UpdateProjectRequest: {
            name?: string;
            description?: string;
            /** @enum {string} */
            status?: "active" | "archived";
        };
        /** @enum {string} */
        ProjectMembershipRole: "owner" | "admin" | "editor" | "reviewer" | "viewer" | "auditor";
        /** @enum {string} */
        ProjectMembershipStatus: "active" | "revoked";
        ProjectMembership: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            actor_id: string;
            role: components["schemas"]["ProjectMembershipRole"];
            status: components["schemas"]["ProjectMembershipStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProjectMembershipResponse: {
            data: components["schemas"]["ProjectMembership"];
        };
        ProjectMembershipListResponse: {
            data: components["schemas"]["ProjectMembership"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        CreateProjectMembershipRequest: {
            actor_id: string;
            role: components["schemas"]["ProjectMembershipRole"];
        };
        UpdateProjectMembershipRequest: {
            role: components["schemas"]["ProjectMembershipRole"];
            github_repo?: string;
        };
        /** @enum {string} */
        MeetingSourceType: "manual" | "discord_log" | "transcript";
        /** @enum {string} */
        ArtifactStatus: "draft" | "generating" | "generated" | "in_review" | "needs_changes" | "approved" | "failed";
        Meeting: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            title: string;
            source_type: components["schemas"]["MeetingSourceType"];
            /** Format: date */
            meeting_date?: string;
            participants?: string[];
            raw_text: string;
            status: components["schemas"]["ArtifactStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        MeetingResponse: {
            data: components["schemas"]["Meeting"];
        };
        MeetingListResponse: {
            data: components["schemas"]["Meeting"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        CreateMeetingRequest: {
            title: string;
            source_type: components["schemas"]["MeetingSourceType"];
            /** Format: date */
            meeting_date?: string;
            participants?: string[];
            raw_text: string;
            tags?: string[];
        };
        /** @enum {string} */
        ConversationImportSourceType: "discord_dm_paste";
        /** @enum {string} */
        ConversationImportStatus: "draft" | "blocked" | "ready_for_ai" | "summarizing" | "summary_draft" | "approved" | "rejected" | "archived";
        /** @enum {string} */
        ConversationSummaryDraftStatus: "draft" | "needs_revision" | "approved" | "rejected" | "stale";
        ConversationParticipant: {
            display_name: string;
            handle?: string;
            /** @enum {string} */
            role?: "requester" | "responder" | "reviewer" | "unknown";
            notes?: string;
        };
        ConversationSafetyFlag: {
            /** @enum {string} */
            type: "personal_data" | "secret" | "credential" | "financial" | "legal" | "consent_missing" | "unknown";
            /** @enum {string} */
            severity: "low" | "medium" | "high";
            /** @enum {string} */
            action: "review_required" | "redaction_required" | "blocked";
            location_hint?: string;
            message?: string;
        };
        ConversationRedactionSuggestion: {
            location_hint: string;
            reason: string;
            suggested_replacement: string;
        };
        ConversationImport: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            source_type: components["schemas"]["ConversationImportSourceType"];
            title: string;
            raw_text: string;
            redacted_text?: string;
            participants: components["schemas"]["ConversationParticipant"][];
            /** Format: date-time */
            conversation_started_at?: string;
            /** Format: date-time */
            conversation_ended_at?: string;
            consent_confirmed: boolean;
            /** Format: uuid */
            consent_confirmed_by?: string;
            /** Format: date-time */
            consent_confirmed_at?: string;
            consent_statement_version: string;
            status: components["schemas"]["ConversationImportStatus"];
            safety_flags: components["schemas"]["ConversationSafetyFlag"][];
            blocked_reasons: string[];
            /** Format: date-time */
            raw_text_retention_expires_at?: string;
            /** Format: date-time */
            raw_text_purged_at?: string;
            /** Format: date-time */
            retention_expires_at?: string;
            /** Format: date-time */
            anonymized_at?: string;
            latest_summary_draft?: components["schemas"]["ConversationSummaryDraft"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ConversationImportResponse: {
            data: components["schemas"]["ConversationImport"];
        };
        ConversationImportListResponse: {
            data: components["schemas"]["ConversationImport"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        CreateConversationImportRequest: {
            source_type: components["schemas"]["ConversationImportSourceType"];
            title: string;
            raw_text: string;
            redacted_text?: string;
            participants?: components["schemas"]["ConversationParticipant"][];
            /** Format: date-time */
            conversation_started_at?: string;
            /** Format: date-time */
            conversation_ended_at?: string;
            consent_confirmed: boolean;
            consent_statement_version: string;
        };
        UpdateConversationImportRequest: {
            title?: string;
            raw_text?: string;
            redacted_text?: string;
            participants?: components["schemas"]["ConversationParticipant"][];
            /** Format: date-time */
            conversation_started_at?: string;
            /** Format: date-time */
            conversation_ended_at?: string;
            consent_confirmed?: boolean;
            consent_statement_version?: string;
        };
        ConversationImportScanResponse: {
            data: {
                valid: boolean;
                conversation_import: components["schemas"]["ConversationImport"];
                safety_flags: components["schemas"]["ConversationSafetyFlag"][];
                blocked_reasons: string[];
                redaction_suggestions: components["schemas"]["ConversationRedactionSuggestion"][];
                /** @enum {string} */
                next_action: "edit_and_rescan" | "generate_summary" | "archive";
            };
        };
        ConversationSourceQuote: {
            id: string;
            quote: string;
            speaker?: string;
            /** Format: date-time */
            message_at?: string;
        };
        ConversationDecision: {
            text: string;
            owner?: string;
            source_quote_ids?: string[];
            confidence: number;
        };
        ConversationActionItem: {
            text: string;
            owner?: string;
            /** Format: date */
            due_date?: string;
            /** @enum {string} */
            status: "open" | "in_progress" | "done";
            source_quote_ids?: string[];
            confidence: number;
        };
        ConversationIssueCandidate: {
            title: string;
            body: string;
            labels?: string[];
            /** @enum {string} */
            priority: "P0" | "P1" | "P2" | "P3";
            source_quote_ids?: string[];
            confidence: number;
        };
        ConversationRequirementCandidate: {
            title: string;
            requirement: string;
            acceptance_criteria: string[];
            source_quote_ids?: string[];
            confidence: number;
        };
        ConversationRisk: {
            text: string;
            /** @enum {string} */
            severity: "low" | "medium" | "high";
            mitigation?: string;
            source_quote_ids?: string[];
            confidence: number;
        };
        ConversationSummaryDraft: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversation_import_id: string;
            status: components["schemas"]["ConversationSummaryDraftStatus"];
            summary: string;
            decisions: components["schemas"]["ConversationDecision"][];
            open_questions: string[];
            action_items: components["schemas"]["ConversationActionItem"][];
            issue_candidates: components["schemas"]["ConversationIssueCandidate"][];
            requirement_candidates: components["schemas"]["ConversationRequirementCandidate"][];
            risks: components["schemas"]["ConversationRisk"][];
            participants: components["schemas"]["ConversationParticipant"][];
            source_quotes: components["schemas"]["ConversationSourceQuote"][];
            confidence: number;
            generated_by_model?: string;
            /** Format: date-time */
            retention_expires_at?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ConversationSummaryDraftResponse: {
            data: components["schemas"]["ConversationSummaryDraft"];
        };
        ConversationSummaryGenerationResponse: {
            data: {
                job: components["schemas"]["Job"];
                conversation_summary_draft?: components["schemas"]["ConversationSummaryDraft"];
            };
        };
        UpdateConversationSummaryDraftRequest: {
            summary?: string;
            decisions?: components["schemas"]["ConversationDecision"][];
            open_questions?: string[];
            action_items?: components["schemas"]["ConversationActionItem"][];
            issue_candidates?: components["schemas"]["ConversationIssueCandidate"][];
            requirement_candidates?: components["schemas"]["ConversationRequirementCandidate"][];
            risks?: components["schemas"]["ConversationRisk"][];
            participants?: components["schemas"]["ConversationParticipant"][];
            status?: components["schemas"]["ConversationSummaryDraftStatus"];
        };
        ApproveConversationSummaryDraftRequest: {
            approval_note: string;
            /** @default true */
            generate_downstream_candidates: boolean;
        };
        Minutes: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            meeting_id: string;
            status: components["schemas"]["ArtifactStatus"];
            summary: string;
            decisions: components["schemas"]["DecisionItem"][];
            open_questions: string[];
            action_items: components["schemas"]["ActionItem"][];
            generated_by_model?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        MinutesResponse: {
            data: components["schemas"]["Minutes"];
        };
        UpdateMinutesRequest: {
            summary?: string;
            decisions?: components["schemas"]["DecisionItem"][];
            open_questions?: string[];
            action_items?: components["schemas"]["ActionItem"][];
            status?: components["schemas"]["ArtifactStatus"];
        };
        DecisionItem: {
            text: string;
            owner?: string;
        };
        ActionItem: {
            text: string;
            owner?: string;
            /** Format: date */
            due_date?: string;
            /** @enum {string} */
            status: "open" | "in_progress" | "done";
        };
        Requirement: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            minutes_id: string;
            status: components["schemas"]["ArtifactStatus"];
            background: string;
            goal: string;
            user_stories?: string[];
            functional_requirements: string[];
            non_functional_requirements?: string[];
            acceptance_criteria: string[];
            out_of_scope?: string[];
            open_questions?: string[];
            risks?: string[];
            generated_by_model?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RequirementResponse: {
            data: components["schemas"]["Requirement"];
        };
        UpdateRequirementRequest: {
            background?: string;
            goal?: string;
            user_stories?: string[];
            functional_requirements?: string[];
            non_functional_requirements?: string[];
            acceptance_criteria?: string[];
            out_of_scope?: string[];
            open_questions?: string[];
            risks?: string[];
            status?: components["schemas"]["ArtifactStatus"];
        };
        /** @enum {string} */
        IssueDraftStatus: "draft" | "in_review" | "needs_changes" | "approved" | "publishing" | "published" | "publish_failed";
        GitHubReconciliationStatus: {
            pending: boolean;
            /** Format: uuid */
            attempt_id?: string;
            /** @enum {string} */
            status?: "reconciliation_required";
            safe_error_code?: string;
            safe_error_detail?: string;
            github_issue_number?: number;
            /** Format: uri */
            github_issue_url?: string;
            reconciliation_retry_count?: number;
            /** Format: date-time */
            next_reconciliation_retry_at?: string;
            reconciliation_cooldown_active?: boolean;
            /** Format: date-time */
            completed_at?: string;
        };
        GitHubReconciliationHistoryItem: {
            /** Format: uuid */
            attempt_id: string;
            /** @enum {string} */
            status: "started" | "github_created" | "local_saved" | "failed" | "reconciliation_required" | "reconciled" | "retry_approved";
            safe_error_code?: string;
            safe_error_detail?: string;
            github_repository?: string;
            github_issue_number?: number;
            /** Format: uri */
            github_issue_url?: string;
            reconciliation_retry_count?: number;
            /** Format: date-time */
            next_reconciliation_retry_at?: string;
            reconciliation_cooldown_active?: boolean;
            retry_approver?: string;
            /** @enum {string} */
            retry_reason_template?: "github_issue_absence_confirmed" | "github_search_complete_no_match" | "provider_transient_failure_confirmed";
            retry_reason_template_label?: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            github_created_at?: string;
            /** Format: date-time */
            completed_at?: string;
            /** Format: date-time */
            reconciled_at?: string;
        };
        IssueDraft: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            requirement_id: string;
            status: components["schemas"]["IssueDraftStatus"];
            title: string;
            body: string;
            acceptance_criteria: string[];
            labels: string[];
            github_issue_number?: number;
            github_issue_url?: string;
            publish_error?: string;
            github_reconciliation?: components["schemas"]["GitHubReconciliationStatus"];
            github_reconciliation_history?: components["schemas"]["GitHubReconciliationHistoryItem"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        IssueDraftResponse: {
            data: components["schemas"]["IssueDraft"];
        };
        UpdateIssueDraftRequest: {
            title?: string;
            body?: string;
            acceptance_criteria?: string[];
            labels?: string[];
            status?: components["schemas"]["IssueDraftStatus"];
        };
        /** @enum {string} */
        OpenApiDraftStatus: "draft" | "invalid" | "valid" | "in_review" | "needs_changes" | "approved";
        OpenApiDraft: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            requirement_id: string;
            status: components["schemas"]["OpenApiDraftStatus"];
            title: string;
            /** @description OpenAPI YAML content */
            content: string;
            validation_errors?: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OpenApiDraftResponse: {
            data: components["schemas"]["OpenApiDraft"];
        };
        OpenApiValidationResponse: {
            data: {
                valid: boolean;
                errors: components["schemas"]["ValidationIssue"][];
                warnings: components["schemas"]["ValidationIssue"][];
            };
        };
        ValidationIssue: {
            path: string;
            message: string;
            /** @enum {string} */
            severity: "error" | "warning";
            code?: string;
        };
        UpdateOpenApiDraftRequest: {
            title?: string;
            content?: string;
            status?: components["schemas"]["OpenApiDraftStatus"];
        };
        /** @enum {string} */
        ReviewTargetType: "meeting" | "conversation_import" | "conversation_summary_draft" | "minutes" | "requirement" | "issue_draft" | "openapi_draft" | "architecture" | "security" | "release";
        /** @enum {string} */
        ReviewStatus: "open" | "action_required" | "resolved" | "accepted_risk";
        Review: {
            /** Format: uuid */
            id: string;
            target_type: components["schemas"]["ReviewTargetType"];
            target_id: string;
            status: components["schemas"]["ReviewStatus"];
            reviewer_role: string;
            framework: string[];
            positives: string[];
            improvements: string[];
            priority: string[];
            next_actions: string[];
            issue_numbers: string[];
            accepted_risk?: components["schemas"]["AcceptedRisk"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ReviewResponse: {
            data: components["schemas"]["Review"];
        };
        ReviewListResponse: {
            data: components["schemas"]["Review"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        CreateReviewRequest: {
            target_type: components["schemas"]["ReviewTargetType"];
            target_id: string;
            reviewer_role: string;
            framework: string[];
            positives: string[];
            improvements: string[];
            priority: string[];
            next_actions: string[];
            issue_numbers: string[];
        };
        ResolveReviewActionRequest: {
            resolution_note: string;
        };
        AcceptReviewRiskRequest: {
            reason: string;
            residual_risk: string;
            /** Format: date-time */
            expires_at: string;
            linked_issue_number: string;
        };
        AcceptedRisk: {
            reason: string;
            residual_risk: string;
            /** Format: uuid */
            approved_by: string;
            /** Format: date-time */
            expires_at: string;
            linked_issue_number: string;
            /** Format: date-time */
            accepted_at: string;
        };
        GenerationJobResponse: {
            data: {
                /** Format: uuid */
                job_id: string;
                /** @enum {string} */
                status: "queued" | "running" | "succeeded";
            };
        };
        Job: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /** @enum {string} */
            job_type: "ai_generation" | "github_publish" | "github_reconciliation" | "github_connect" | "validation";
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            target_type: string;
            target_id?: string;
            progress?: number;
            error_code?: string;
            error_message?: string;
            safe_error_detail?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        JobResponse: {
            data: components["schemas"]["Job"];
        };
        /** @enum {string} */
        QueueHealthStatus: "healthy" | "degraded" | "unavailable";
        QueueWorkerSummary: {
            kind: string;
            name: string;
            hostname?: string;
            /** Format: date-time */
            last_heartbeat_at: string;
            stale: boolean;
        };
        QueueSummary: {
            queue_name: string;
            unfinished_count: number;
            /** Format: date-time */
            oldest_unfinished_at?: string;
            oldest_unfinished_age_seconds?: number;
        };
        FailedExecutionSummary: {
            count: number;
            /** Format: date-time */
            latest_failed_at?: string;
        };
        FailedJobSample: {
            queue_name: string;
            class_name: string;
            active_job_id?: string;
            /** Format: date-time */
            failed_at: string;
        };
        RecurringTaskSummary: {
            key: string;
            class_name?: string;
            queue_name?: string;
            schedule?: string;
        };
        ProductJobStatusSummary: {
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            count: number;
        };
        ProductJobsSummary: {
            by_status: components["schemas"]["ProductJobStatusSummary"][];
            recent_failed_count: number;
        };
        QueueHealth: {
            status: components["schemas"]["QueueHealthStatus"];
            /** Format: date-time */
            checked_at: string;
            heartbeat_stale_after_seconds: number;
            oldest_unfinished_threshold_seconds: number;
            workers: components["schemas"]["QueueWorkerSummary"][];
            queues: components["schemas"]["QueueSummary"][];
            failed_executions: components["schemas"]["FailedExecutionSummary"];
            failed_job_samples: components["schemas"]["FailedJobSample"][];
            recurring_tasks: components["schemas"]["RecurringTaskSummary"][];
            product_jobs: components["schemas"]["ProductJobsSummary"];
            warnings: string[];
        };
        QueueHealthResponse: {
            data: components["schemas"]["QueueHealth"];
        };
        PublishGitHubIssueResponse: {
            data: {
                /** @enum {string} */
                status: "publishing" | "published";
                github_issue_number?: number;
                github_issue_url?: string;
                /** Format: uuid */
                attempt_id?: string;
            };
        };
        ReconcileGitHubIssueResponse: {
            data: {
                /** Format: uuid */
                job_id: string;
                /** @enum {string} */
                status: "reconciled" | "review_required";
                /** Format: uuid */
                attempt_id: string;
                match_count: number;
                search_total_count?: number;
                search_incomplete_results?: boolean;
                search_result_limit?: number;
                search_has_more_results?: boolean;
                reconciliation_retry_count?: number;
                /** Format: date-time */
                next_reconciliation_retry_at?: string;
                reconciliation_cooldown_active?: boolean;
                /** Format: uuid */
                review_id?: string;
                matches?: components["schemas"]["GitHubReconciliationMatch"][];
                github_issue_number?: number;
                github_issue_url?: string;
            };
        };
        GitHubReconciliationMatch: {
            github_issue_number: number;
            /** Format: uri */
            github_issue_url: string;
            github_repository: string;
            github_issue_title?: string;
            /** @enum {string} */
            github_issue_state?: "open" | "closed";
            /** Format: date-time */
            github_issue_updated_at?: string;
            github_issue_score?: number;
            github_issue_api_id?: number;
            github_issue_node_id?: string;
        };
        ResolveGitHubReconciliationRequest: {
            /** Format: uuid */
            attempt_id?: string;
            /** @enum {string} */
            resolution_action: "link_existing_issue" | "approve_retry";
            resolution_note: string;
            /** @description Required when resolution_action is approve_retry. */
            resolution_approver?: string;
            /**
             * @description Required when resolution_action is approve_retry.
             * @enum {string}
             */
            retry_reason_template?: "github_issue_absence_confirmed" | "github_search_complete_no_match" | "provider_transient_failure_confirmed";
            github_issue_number?: number;
            /** Format: uri */
            github_issue_url?: string;
            github_issue_api_id?: number;
            github_issue_node_id?: string;
        };
        ResolveGitHubReconciliationResponse: {
            data: {
                /** Format: uuid */
                job_id: string;
                /** @enum {string} */
                status: "manually_reconciled" | "retry_approved";
                /** Format: uuid */
                attempt_id: string;
                /** Format: uuid */
                review_id?: string;
                resolution_approver?: string;
                /** @enum {string} */
                retry_reason_template?: "github_issue_absence_confirmed" | "github_search_complete_no_match" | "provider_transient_failure_confirmed";
                github_issue_number?: number;
                github_issue_url?: string;
            };
        };
        /** @enum {string} */
        IntegrationProvider: "github" | "discord" | "notion" | "google_drive" | "slack";
        IntegrationAccount: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            provider: components["schemas"]["IntegrationProvider"];
            /** @enum {string} */
            status: "not_connected" | "connected" | "error" | "revoked";
            external_account_id?: string;
            repository_owner: string;
            repository_name: string;
            github_installation_id?: string;
            github_account_login?: string;
            github_account_type?: string;
            granted_permissions: {
                [key: string]: "read" | "write";
            };
            /** Format: date-time */
            last_sync_at?: string;
            last_error_safe?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        IntegrationAccountResponse: {
            data: components["schemas"]["IntegrationAccount"];
        };
        StartGitHubConnectionRequest: {
            /** @description GitHub repository in owner/name format. */
            repository: string;
            /** Format: uri */
            redirect_uri?: string;
        };
        StartGitHubConnectionResponse: {
            data: {
                /** Format: uri */
                installation_url: string;
                state: string;
                /** Format: date-time */
                expires_at: string;
            };
        };
        GitHubCallbackRequest: {
            installation_id: string;
            state: string;
            /** @enum {string} */
            setup_action?: "install" | "update";
            account_login?: string;
            account_type?: string;
            granted_permissions?: {
                [key: string]: "read" | "write";
            };
        };
        WebhookAcceptedResponse: {
            data: {
                delivery_id: string;
                /** @enum {string} */
                status: "accepted" | "duplicate_ignored";
            };
        };
        AuditLog: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            actor_id: string;
            action: string;
            target_type: string;
            target_id: string;
            summary?: string;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        AuditLogListResponse: {
            data: components["schemas"]["AuditLog"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        PaginationMeta: {
            page: number;
            per_page: number;
            total_count: number;
            total_pages: number;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
            request_id: string;
        };
    };
    responses: {
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication or signature verification failed */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Actor is not allowed to perform this action in the project */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request conflicts with current project state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Review or approval is required before this action */
        ReviewRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Required integration is not connected */
        IntegrationNotConnected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Upstream AI provider failed or returned an invalid response */
        UpstreamError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        ProjectId: string;
        MembershipId: string;
        MeetingId: string;
        ConversationImportId: string;
        ConversationSummaryDraftId: string;
        MinutesId: string;
        RequirementId: string;
        IssueDraftId: string;
        OpenApiDraftId: string;
        ReviewId: string;
        JobId: string;
        Page: number;
        PerPage: number;
        MembershipStatusFilter: "active" | "revoked" | "all";
        IdempotencyKey: string;
        GitHubEvent: string;
        GitHubDelivery: string;
        GitHubSignature256: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    archiveProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Project updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    listProjectMemberships: {
        parameters: {
            query?: {
                status?: components["parameters"]["MembershipStatusFilter"];
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project memberships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMembershipListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createProjectMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectMembershipRequest"];
            };
        };
        responses: {
            /** @description Project membership created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMembershipResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    revokeProjectMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                membership_id: components["parameters"]["MembershipId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project membership revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateProjectMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                membership_id: components["parameters"]["MembershipId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectMembershipRequest"];
            };
        };
        responses: {
            /** @description Project membership updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMembershipResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listProjectMeetings: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meetings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMeetingRequest"];
            };
        };
        responses: {
            /** @description Meeting created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    listProjectConversationImports: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation imports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationImportListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createConversationImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationImportRequest"];
            };
        };
        responses: {
            /** @description Conversation import created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationImportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    getConversationImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_import_id: components["parameters"]["ConversationImportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation import */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationImportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    anonymizeConversationImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_import_id: components["parameters"]["ConversationImportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation import anonymized */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateConversationImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_import_id: components["parameters"]["ConversationImportId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConversationImportRequest"];
            };
        };
        responses: {
            /** @description Conversation import updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationImportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    scanConversationImport: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                conversation_import_id: components["parameters"]["ConversationImportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scan result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationImportScanResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    generateConversationSummary: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                conversation_import_id: components["parameters"]["ConversationImportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation summary generation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummaryGenerationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            424: components["responses"]["IntegrationNotConnected"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["UpstreamError"];
        };
    };
    getConversationSummaryDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_summary_draft_id: components["parameters"]["ConversationSummaryDraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation summary draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummaryDraftResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateConversationSummaryDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_summary_draft_id: components["parameters"]["ConversationSummaryDraftId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConversationSummaryDraftRequest"];
            };
        };
        responses: {
            /** @description Conversation summary draft updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummaryDraftResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    approveConversationSummaryDraft: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                conversation_summary_draft_id: components["parameters"]["ConversationSummaryDraftId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveConversationSummaryDraftRequest"];
            };
        };
        responses: {
            /** @description Conversation summary draft approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummaryDraftResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    getMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: components["parameters"]["MeetingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meeting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    generateMinutes: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                meeting_id: components["parameters"]["MeetingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Minutes generation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            424: components["responses"]["IntegrationNotConnected"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["UpstreamError"];
        };
    };
    getMinutes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minutes_id: components["parameters"]["MinutesId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Minutes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinutesResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateMinutes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minutes_id: components["parameters"]["MinutesId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMinutesRequest"];
            };
        };
        responses: {
            /** @description Minutes updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinutesResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    approveMinutes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minutes_id: components["parameters"]["MinutesId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Minutes approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinutesResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["ReviewRequired"];
        };
    };
    generateRequirement: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                minutes_id: components["parameters"]["MinutesId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requirement generation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobResponse"];
                };
            };
            409: components["responses"]["ReviewRequired"];
        };
    };
    getRequirement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requirement_id: components["parameters"]["RequirementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requirement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateRequirement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requirement_id: components["parameters"]["RequirementId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRequirementRequest"];
            };
        };
        responses: {
            /** @description Requirement updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    approveRequirement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requirement_id: components["parameters"]["RequirementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requirement approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["ReviewRequired"];
        };
    };
    generateIssueDraft: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                requirement_id: components["parameters"]["RequirementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue draft generation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobResponse"];
                };
            };
            409: components["responses"]["ReviewRequired"];
        };
    };
    generateOpenApiDraft: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                requirement_id: components["parameters"]["RequirementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI draft generation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobResponse"];
                };
            };
            409: components["responses"]["ReviewRequired"];
        };
    };
    getIssueDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue_draft_id: components["parameters"]["IssueDraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDraftResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateIssueDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue_draft_id: components["parameters"]["IssueDraftId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIssueDraftRequest"];
            };
        };
        responses: {
            /** @description Issue draft updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDraftResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    publishIssueDraftToGitHub: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                issue_draft_id: components["parameters"]["IssueDraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Publish accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishGitHubIssueResponse"];
                };
            };
            409: components["responses"]["ReviewRequired"];
            424: components["responses"]["IntegrationNotConnected"];
        };
    };
    reconcileGitHubIssuePublish: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                issue_draft_id: components["parameters"]["IssueDraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reconciliation completed or requires human review */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconcileGitHubIssueResponse"];
                };
            };
            409: components["responses"]["ReviewRequired"];
            424: components["responses"]["IntegrationNotConnected"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["UpstreamError"];
        };
    };
    resolveGitHubIssueReconciliation: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                issue_draft_id: components["parameters"]["IssueDraftId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveGitHubReconciliationRequest"];
            };
        };
        responses: {
            /** @description Manual reconciliation resolved */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveGitHubReconciliationResponse"];
                };
            };
            409: components["responses"]["ReviewRequired"];
            422: components["responses"]["ValidationError"];
        };
    };
    getOpenApiDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                openapi_draft_id: components["parameters"]["OpenApiDraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenApiDraftResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateOpenApiDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                openapi_draft_id: components["parameters"]["OpenApiDraftId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOpenApiDraftRequest"];
            };
        };
        responses: {
            /** @description OpenAPI draft updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenApiDraftResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    validateOpenApiDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                openapi_draft_id: components["parameters"]["OpenApiDraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenApiValidationResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listReviews: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
                target_type?: components["schemas"]["ReviewTargetType"];
                target_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reviews */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewRequest"];
            };
        };
        responses: {
            /** @description Review created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    resolveReviewAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveReviewActionRequest"];
            };
        };
        responses: {
            /** @description Review updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    acceptReviewRisk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptReviewRiskRequest"];
            };
        };
        responses: {
            /** @description Review marked as accepted risk */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    listProjectIntegrations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Integrations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["IntegrationAccount"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    startGitHubConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartGitHubConnectionRequest"];
            };
        };
        responses: {
            /** @description GitHub connection URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartGitHubConnectionResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    disconnectGitHubIntegration: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GitHub integration disconnected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationAccountResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    completeGitHubConnectionCallback: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitHubCallbackRequest"];
            };
        };
        responses: {
            /** @description GitHub integration connected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationAccountResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            424: components["responses"]["IntegrationNotConnected"];
            502: components["responses"]["UpstreamError"];
        };
    };
    receiveGitHubWebhook: {
        parameters: {
            query?: never;
            header: {
                "X-GitHub-Event": components["parameters"]["GitHubEvent"];
                "X-GitHub-Delivery": components["parameters"]["GitHubDelivery"];
                "X-Hub-Signature-256": components["parameters"]["GitHubSignature256"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Webhook accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAcceptedResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getQueueHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queue health summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueHealthResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listProjectAuditLogs: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
