/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["listProjects"];
        put?: never;
        /** Create project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /** Archive project */
        delete: operations["archiveProject"];
        options?: never;
        head?: never;
        /** Update project */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{project_id}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List meetings in project */
        get: operations["listProjectMeetings"];
        put?: never;
        /** Create meeting */
        post: operations["createMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get meeting */
        get: operations["getMeeting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{meeting_id}/generate-minutes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate minutes from a meeting */
        post: operations["generateMinutes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/minutes/{minutes_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get minutes */
        get: operations["getMinutes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update minutes */
        patch: operations["updateMinutes"];
        trace?: never;
    };
    "/minutes/{minutes_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve minutes */
        post: operations["approveMinutes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/minutes/{minutes_id}/generate-requirement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate requirement from minutes */
        post: operations["generateRequirement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requirements/{requirement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get requirement */
        get: operations["getRequirement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update requirement */
        patch: operations["updateRequirement"];
        trace?: never;
    };
    "/requirements/{requirement_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve requirement */
        post: operations["approveRequirement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requirements/{requirement_id}/generate-issue-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate GitHub issue draft from requirement */
        post: operations["generateIssueDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requirements/{requirement_id}/generate-openapi-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate OpenAPI draft from requirement */
        post: operations["generateOpenApiDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issue-drafts/{issue_draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get issue draft */
        get: operations["getIssueDraft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update issue draft */
        patch: operations["updateIssueDraft"];
        trace?: never;
    };
    "/issue-drafts/{issue_draft_id}/publish-github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish approved issue draft to GitHub */
        post: operations["publishIssueDraftToGitHub"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi-drafts/{openapi_draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get OpenAPI draft */
        get: operations["getOpenApiDraft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update OpenAPI draft */
        patch: operations["updateOpenApiDraft"];
        trace?: never;
    };
    "/openapi-drafts/{openapi_draft_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate OpenAPI draft */
        post: operations["validateOpenApiDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reviews */
        get: operations["listReviews"];
        put?: never;
        /** Create review */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}/resolve-action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark review action resolved */
        post: operations["resolveReviewAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}/accept-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark review blocker as accepted risk */
        post: operations["acceptReviewRisk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List project integrations */
        get: operations["listProjectIntegrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/integrations/github/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start GitHub connection */
        post: operations["startGitHubConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/integrations/github/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disconnect GitHub integration */
        post: operations["disconnectGitHubIntegration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete GitHub connection callback */
        post: operations["completeGitHubConnectionCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive GitHub App webhook */
        post: operations["receiveGitHubWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get generation or integration job */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit logs */
        get: operations["listProjectAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string;
            /** @enum {string} */
            status: "active" | "archived";
            github_repo?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProjectResponse: {
            data: components["schemas"]["Project"];
        };
        ProjectListResponse: {
            data: components["schemas"]["Project"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        CreateProjectRequest: {
            name: string;
            description?: string;
            github_repo?: string;
        };
        UpdateProjectRequest: {
            name?: string;
            description?: string;
            /** @enum {string} */
            status?: "active" | "archived";
            github_repo?: string;
        };
        /** @enum {string} */
        MeetingSourceType: "manual" | "discord_log" | "transcript";
        /** @enum {string} */
        ArtifactStatus: "draft" | "generating" | "generated" | "in_review" | "needs_changes" | "approved" | "failed";
        Meeting: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            title: string;
            source_type: components["schemas"]["MeetingSourceType"];
            /** Format: date */
            meeting_date?: string;
            participants?: string[];
            raw_text: string;
            status: components["schemas"]["ArtifactStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        MeetingResponse: {
            data: components["schemas"]["Meeting"];
        };
        MeetingListResponse: {
            data: components["schemas"]["Meeting"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        CreateMeetingRequest: {
            title: string;
            source_type: components["schemas"]["MeetingSourceType"];
            /** Format: date */
            meeting_date?: string;
            participants?: string[];
            raw_text: string;
            tags?: string[];
        };
        Minutes: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            meeting_id: string;
            status: components["schemas"]["ArtifactStatus"];
            summary: string;
            decisions: components["schemas"]["DecisionItem"][];
            open_questions: string[];
            action_items: components["schemas"]["ActionItem"][];
            generated_by_model?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        MinutesResponse: {
            data: components["schemas"]["Minutes"];
        };
        UpdateMinutesRequest: {
            summary?: string;
            decisions?: components["schemas"]["DecisionItem"][];
            open_questions?: string[];
            action_items?: components["schemas"]["ActionItem"][];
            status?: components["schemas"]["ArtifactStatus"];
        };
        DecisionItem: {
            text: string;
            owner?: string;
        };
        ActionItem: {
            text: string;
            owner?: string;
            /** Format: date */
            due_date?: string;
            /** @enum {string} */
            status: "open" | "in_progress" | "done";
        };
        Requirement: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            minutes_id: string;
            status: components["schemas"]["ArtifactStatus"];
            background: string;
            goal: string;
            user_stories?: string[];
            functional_requirements: string[];
            non_functional_requirements?: string[];
            acceptance_criteria: string[];
            out_of_scope?: string[];
            open_questions?: string[];
            risks?: string[];
            generated_by_model?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RequirementResponse: {
            data: components["schemas"]["Requirement"];
        };
        UpdateRequirementRequest: {
            background?: string;
            goal?: string;
            user_stories?: string[];
            functional_requirements?: string[];
            non_functional_requirements?: string[];
            acceptance_criteria?: string[];
            out_of_scope?: string[];
            open_questions?: string[];
            risks?: string[];
            status?: components["schemas"]["ArtifactStatus"];
        };
        /** @enum {string} */
        IssueDraftStatus: "draft" | "in_review" | "needs_changes" | "approved" | "publishing" | "published" | "publish_failed";
        IssueDraft: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            requirement_id: string;
            status: components["schemas"]["IssueDraftStatus"];
            title: string;
            body: string;
            acceptance_criteria: string[];
            labels: string[];
            github_issue_number?: number;
            github_issue_url?: string;
            publish_error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        IssueDraftResponse: {
            data: components["schemas"]["IssueDraft"];
        };
        UpdateIssueDraftRequest: {
            title?: string;
            body?: string;
            acceptance_criteria?: string[];
            labels?: string[];
            status?: components["schemas"]["IssueDraftStatus"];
        };
        /** @enum {string} */
        OpenApiDraftStatus: "draft" | "invalid" | "valid" | "in_review" | "needs_changes" | "approved";
        OpenApiDraft: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            requirement_id: string;
            status: components["schemas"]["OpenApiDraftStatus"];
            title: string;
            /** @description OpenAPI YAML content */
            content: string;
            validation_errors?: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OpenApiDraftResponse: {
            data: components["schemas"]["OpenApiDraft"];
        };
        OpenApiValidationResponse: {
            data: {
                valid: boolean;
                errors: components["schemas"]["ValidationIssue"][];
                warnings: components["schemas"]["ValidationIssue"][];
            };
        };
        ValidationIssue: {
            path: string;
            message: string;
            /** @enum {string} */
            severity: "error" | "warning";
            code?: string;
        };
        UpdateOpenApiDraftRequest: {
            title?: string;
            content?: string;
            status?: components["schemas"]["OpenApiDraftStatus"];
        };
        /** @enum {string} */
        ReviewTargetType: "meeting" | "minutes" | "requirement" | "issue_draft" | "openapi_draft" | "architecture" | "security" | "release";
        /** @enum {string} */
        ReviewStatus: "open" | "action_required" | "resolved" | "accepted_risk";
        Review: {
            /** Format: uuid */
            id: string;
            target_type: components["schemas"]["ReviewTargetType"];
            target_id: string;
            status: components["schemas"]["ReviewStatus"];
            reviewer_role: string;
            framework: string[];
            positives: string[];
            improvements: string[];
            priority: string[];
            next_actions: string[];
            issue_numbers: string[];
            accepted_risk?: components["schemas"]["AcceptedRisk"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ReviewResponse: {
            data: components["schemas"]["Review"];
        };
        ReviewListResponse: {
            data: components["schemas"]["Review"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        CreateReviewRequest: {
            target_type: components["schemas"]["ReviewTargetType"];
            target_id: string;
            reviewer_role: string;
            framework: string[];
            positives: string[];
            improvements: string[];
            priority: string[];
            next_actions: string[];
            issue_numbers: string[];
        };
        ResolveReviewActionRequest: {
            resolution_note: string;
        };
        AcceptReviewRiskRequest: {
            reason: string;
            residual_risk: string;
            /** Format: date-time */
            expires_at: string;
            linked_issue_number: string;
        };
        AcceptedRisk: {
            reason: string;
            residual_risk: string;
            /** Format: uuid */
            approved_by: string;
            /** Format: date-time */
            expires_at: string;
            linked_issue_number: string;
            /** Format: date-time */
            accepted_at: string;
        };
        GenerationJobResponse: {
            data: {
                /** Format: uuid */
                job_id: string;
                /** @enum {string} */
                status: "queued" | "running" | "succeeded";
            };
        };
        Job: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /** @enum {string} */
            job_type: "ai_generation" | "github_publish" | "github_connect" | "validation";
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            target_type: string;
            target_id?: string;
            progress?: number;
            error_code?: string;
            error_message?: string;
            safe_error_detail?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        JobResponse: {
            data: components["schemas"]["Job"];
        };
        PublishGitHubIssueResponse: {
            data: {
                /** @enum {string} */
                status: "publishing" | "published";
                github_issue_number?: number;
                github_issue_url?: string;
            };
        };
        /** @enum {string} */
        IntegrationProvider: "github" | "discord" | "notion" | "google_drive" | "slack";
        IntegrationAccount: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            provider: components["schemas"]["IntegrationProvider"];
            /** @enum {string} */
            status: "not_connected" | "connected" | "error" | "revoked";
            scopes: string[];
            /** Format: date-time */
            last_sync_at?: string;
            last_error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        IntegrationAccountResponse: {
            data: components["schemas"]["IntegrationAccount"];
        };
        StartGitHubConnectionRequest: {
            /** @description GitHub repository in owner/name format. */
            repository: string;
            /** Format: uri */
            redirect_uri?: string;
        };
        StartGitHubConnectionResponse: {
            data: {
                /** Format: uri */
                authorization_url: string;
                state: string;
            };
        };
        GitHubCallbackRequest: {
            code: string;
            state: string;
        };
        WebhookAcceptedResponse: {
            data: {
                delivery_id: string;
                /** @enum {string} */
                status: "accepted" | "duplicate_ignored";
            };
        };
        AuditLog: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            actor_id: string;
            action: string;
            target_type: string;
            target_id: string;
            summary?: string;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        AuditLogListResponse: {
            data: components["schemas"]["AuditLog"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        PaginationMeta: {
            page: number;
            per_page: number;
            total_count: number;
            total_pages: number;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
            request_id: string;
        };
    };
    responses: {
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication or signature verification failed */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Review or approval is required before this action */
        ReviewRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Required integration is not connected */
        IntegrationNotConnected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Upstream AI provider failed or returned an invalid response */
        UpstreamError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        ProjectId: string;
        MeetingId: string;
        MinutesId: string;
        RequirementId: string;
        IssueDraftId: string;
        OpenApiDraftId: string;
        ReviewId: string;
        JobId: string;
        Page: number;
        PerPage: number;
        IdempotencyKey: string;
        GitHubEvent: string;
        GitHubDelivery: string;
        GitHubSignature256: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    archiveProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Project updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    listProjectMeetings: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meetings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMeetingRequest"];
            };
        };
        responses: {
            /** @description Meeting created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: components["parameters"]["MeetingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meeting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    generateMinutes: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                meeting_id: components["parameters"]["MeetingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Minutes generation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            424: components["responses"]["IntegrationNotConnected"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["UpstreamError"];
        };
    };
    getMinutes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minutes_id: components["parameters"]["MinutesId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Minutes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinutesResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateMinutes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minutes_id: components["parameters"]["MinutesId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMinutesRequest"];
            };
        };
        responses: {
            /** @description Minutes updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinutesResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    approveMinutes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minutes_id: components["parameters"]["MinutesId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Minutes approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinutesResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["ReviewRequired"];
        };
    };
    generateRequirement: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                minutes_id: components["parameters"]["MinutesId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requirement generation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobResponse"];
                };
            };
            409: components["responses"]["ReviewRequired"];
        };
    };
    getRequirement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requirement_id: components["parameters"]["RequirementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requirement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateRequirement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requirement_id: components["parameters"]["RequirementId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRequirementRequest"];
            };
        };
        responses: {
            /** @description Requirement updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    approveRequirement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requirement_id: components["parameters"]["RequirementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requirement approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["ReviewRequired"];
        };
    };
    generateIssueDraft: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                requirement_id: components["parameters"]["RequirementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue draft generation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobResponse"];
                };
            };
            409: components["responses"]["ReviewRequired"];
        };
    };
    generateOpenApiDraft: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                requirement_id: components["parameters"]["RequirementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI draft generation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobResponse"];
                };
            };
            409: components["responses"]["ReviewRequired"];
        };
    };
    getIssueDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue_draft_id: components["parameters"]["IssueDraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDraftResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateIssueDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue_draft_id: components["parameters"]["IssueDraftId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIssueDraftRequest"];
            };
        };
        responses: {
            /** @description Issue draft updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDraftResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    publishIssueDraftToGitHub: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                issue_draft_id: components["parameters"]["IssueDraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Publish accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishGitHubIssueResponse"];
                };
            };
            409: components["responses"]["ReviewRequired"];
            424: components["responses"]["IntegrationNotConnected"];
        };
    };
    getOpenApiDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                openapi_draft_id: components["parameters"]["OpenApiDraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenApiDraftResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateOpenApiDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                openapi_draft_id: components["parameters"]["OpenApiDraftId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOpenApiDraftRequest"];
            };
        };
        responses: {
            /** @description OpenAPI draft updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenApiDraftResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    validateOpenApiDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                openapi_draft_id: components["parameters"]["OpenApiDraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenApiValidationResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listReviews: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
                target_type?: components["schemas"]["ReviewTargetType"];
                target_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reviews */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewRequest"];
            };
        };
        responses: {
            /** @description Review created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    resolveReviewAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveReviewActionRequest"];
            };
        };
        responses: {
            /** @description Review updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    acceptReviewRisk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptReviewRiskRequest"];
            };
        };
        responses: {
            /** @description Review marked as accepted risk */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    listProjectIntegrations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Integrations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["IntegrationAccount"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    startGitHubConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartGitHubConnectionRequest"];
            };
        };
        responses: {
            /** @description GitHub connection URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartGitHubConnectionResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    disconnectGitHubIntegration: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GitHub integration disconnected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationAccountResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    completeGitHubConnectionCallback: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitHubCallbackRequest"];
            };
        };
        responses: {
            /** @description GitHub integration connected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationAccountResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    receiveGitHubWebhook: {
        parameters: {
            query?: never;
            header: {
                "X-GitHub-Event": components["parameters"]["GitHubEvent"];
                "X-GitHub-Delivery": components["parameters"]["GitHubDelivery"];
                "X-Hub-Signature-256": components["parameters"]["GitHubSignature256"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Webhook accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAcceptedResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listProjectAuditLogs: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
