const messageLabels: Record<string, string> = {
  "AI response did not include generated DM summary.": "AI応答に生成済みDM整理が含まれていませんでした。",
  "AI response did not include generated minutes.": "AI応答に生成済み議事録が含まれていませんでした。",
  "AI response did not include generated requirements.": "AI応答に生成済み要件定義が含まれていませんでした。",
  "AI response did not match the expected DM summary schema.": "AI応答が想定されたDM整理形式に一致しませんでした。",
  "AI response did not match the expected minutes schema.": "AI応答が想定された議事録形式に一致しませんでした。",
  "AI response did not match the expected requirement schema.": "AI応答が想定された要件定義形式に一致しませんでした。",
  "A resolution note is required for manual GitHub reconciliation.": "GitHub照合の解決メモを入力してください。",
  "A valid GitHub reconciliation action is required.": "GitHub照合の操作を選択してください。",
  "GitHub integration is not connected.": "GitHub連携が未接続です。",
  "GitHub App is not configured.": "GitHub App設定が未完了です。",
  "GitHub App is not installed for the selected repository.": "選択したリポジトリにGitHub Appがインストールされていません。",
  "GitHub App private key is invalid.": "GitHub App秘密鍵が不正です。",
  "GitHub App requires Issues write permission.": "GitHub AppにIssues書き込み権限が必要です。",
  "GitHub API is temporarily unreachable.": "GitHub APIへ一時的に接続できません。",
  "GitHub API returned an invalid response.": "GitHub APIから不正な応答が返されました。",
  "GitHub connection state already used.": "GitHub接続リンクは使用済みです。ワークスペースから接続をやり直してください。",
  "GitHub connection state expired.": "GitHub接続リンクの有効期限が切れました。ワークスペースから接続をやり直してください。",
  "GitHub connection state is invalid.": "GitHub接続リンクが無効です。ワークスペースから接続をやり直してください。",
  "GitHub installation could not be verified.": "GitHub Appのインストールを確認できませんでした。",
  "GitHub installation token could not be created.": "GitHub Appの一時トークンを作成できませんでした。",
  "GitHub installation token response was invalid.": "GitHub Appの一時トークン応答が不正です。",
  "GitHub Issue creation failed.": "GitHub Issueの作成に失敗しました。",
  "GitHub Issue marker search failed.": "GitHub Issueマーカー検索に失敗しました。",
  "GitHub issue number must be a valid integer.": "GitHub Issue番号は整数で入力してください。",
  "GitHub reconciliation retry is cooling down.": "GitHub照合の再試行待機中です。",
  "GitHub reconciliation action is invalid.": "GitHub照合の操作が不正です。",
  "GitHub publish reconciliation attempt is not pending.": "GitHub公開の照合待ち状態ではありません。",
  "GitHub issue URL must match the project repository and issue number.": "GitHub Issue URLはプロジェクトのリポジトリとIssue番号に一致している必要があります。",
  "GitHub issue may have been created. Reconciliation is required.": "GitHub Issueが作成済みの可能性があります。照合が必要です。",
  "GitHub publish reconciliation blocker must be resolved before publishing.": "GitHub公開の照合ブロッカーを解決してから公開してください。",
  "GitHub rate limit is active. Retry after the provider limit resets.": "GitHubのレート制限中です。制限解除後に再試行してください。",
  "GitHub repository access could not be verified.": "GitHubリポジトリへのアクセスを確認できませんでした。",
  "GitHub repository is not configured for this project.": "このプロジェクトのGitHubリポジトリが未設定です。",
  "A retry approver is required for controlled GitHub publish retry.": "GitHub再試行の承認者を入力してください。",
  "A retry reason template is required for controlled GitHub publish retry.": "GitHub再試行の理由テンプレートを選択してください。",
  "Issue draft must be approved before publishing.": "公開前にIssueドラフトを承認してください。",
  "Meeting text includes sensitive content that must be reviewed before AI generation.": "会議ログに機密性の高い内容が含まれています。AI生成前にレビューしてください。",
  "Minutes must be approved before generating requirements.": "要件定義を生成する前に議事録を承認してください。",
  "Minutes generation provider is not supported.": "議事録生成providerがサポートされていません。",
  "Multiple GitHub Issue marker matches were found.": "GitHub Issueマーカー候補が複数見つかりました。",
  "No GitHub publish reconciliation attempt is pending.": "GitHub公開の照合待ち試行がありません。",
  "OpenAI API key is not configured.": "OpenAI APIキーが未設定です。",
  "OpenAI request failed before a response was received.": "OpenAIから応答を受け取る前にリクエストが失敗しました。",
  "OpenAI request failed. Retry later or check integration settings.": "OpenAIリクエストに失敗しました。時間を置いて再試行するか、連携設定を確認してください。",
  "OpenAI request was rate limited. Retry after the provider limit resets.": "OpenAIのレート制限に達しました。制限解除後に再試行してください。",
  "OpenAPI draft must be valid before publishing.": "公開前にOpenAPIドラフトを検証済みにしてください。",
  "OpenAPI validation blocker must be resolved before publishing.": "公開前にOpenAPI検証ブロッカーを解決してください。",
  "OpenAPI validation could not be completed.": "OpenAPI検証を完了できませんでした。",
  "Reconciliation required.": "照合が必要です。",
  "Repository does not match the project GitHub repository.": "リポジトリがプロジェクトのGitHubリポジトリと一致していません。",
  "Requirement must be approved before generating an OpenAPI draft.": "OpenAPIドラフト生成前に要件定義を承認してください。",
  "Requirement must be approved before generating issue drafts.": "Issueドラフト生成前に要件定義を承認してください。",
  "Requirement generation provider is not supported.": "要件定義生成providerがサポートされていません。",
  "Requirement open questions must be resolved before approval.": "要件定義の未決事項を解決してから承認してください。",
  "Resource not found": "対象のリソースが見つかりません。",
  "Review target must belong to a project-scoped workflow resource.": "レビュー対象はプロジェクト配下のワークフローリソースである必要があります。",
  "Resolution note is too long for manual GitHub reconciliation.": "GitHub照合の解決メモが長すぎます。",
  "Retry approver is too long for controlled GitHub publish retry.": "GitHub再試行の承認者名が長すぎます。",
  "Retry reason template is invalid for controlled GitHub publish retry.": "GitHub再試行の理由テンプレートが不正です。",
  "Valid OpenAPI draft is required before publishing.": "公開前に有効なOpenAPIドラフトが必要です。",
  "project_id is required.": "project_idが必要です。",
  "project_id is required when no review target is specified.": "レビュー対象を指定しない場合はproject_idが必要です。",
  "Conversation import must be scanned before AI summary generation.": "DMインポートはAI整理前にスキャンしてください。",
  "Conversation import is blocked by safety checks.": "DMインポートは安全チェックでブロックされています。",
  "Conversation import has been anonymized.": "DMインポートは匿名化済みです。",
  "Conversation import anonymization failed.": "DMインポートの匿名化に失敗しました。時間を置いて再試行してください。",
  "Conversation import access is forbidden.": "DMインポートを操作する権限がありません。",
  "Conversation import actor is required.": "DMインポート操作には利用者情報が必要です。",
  "Authentication is required.": "ログインが必要です。もう一度ログインしてください。",
  "Authentication token is invalid.": "ログイン情報が無効です。もう一度ログインしてください。",
  "Authentication token has expired.": "ログインの有効期限が切れました。もう一度ログインしてください。",
  "Authentication token is not active yet.": "ログイン情報がまだ有効ではありません。時間を確認して再ログインしてください。",
  "Authentication token has been revoked.": "ログイン情報は失効しています。もう一度ログインしてください。",
  "Authentication session was not found.": "ログインセッションを確認できませんでした。もう一度ログインしてください。",
  "Authentication session has expired.": "ログインセッションの有効期限が切れました。もう一度ログインしてください。",
  "Authentication session has been revoked.": "ログインセッションは失効しています。もう一度ログインしてください。",
  "Authentication session is no longer current.": "ログイン状態が更新されています。もう一度ログインしてください。",
  "Authentication token key is unknown.": "ログイン情報を確認できませんでした。もう一度ログインしてください。",
  "Authentication token key has been retired.": "ログイン情報の署名鍵が更新されています。もう一度ログインしてください。",
  "Authentication token key is not active.": "ログイン情報を確認できませんでした。もう一度ログインしてください。",
  "Authentication is not configured.": "認証設定が未完了です。管理者に確認してください。",
  "Project access is forbidden.": "このプロジェクトを操作する権限がありません。",
  "Project membership access is forbidden.": "プロジェクトメンバーを管理する権限がありません。",
  "Project membership owner permission is required.": "所有者権限が必要です。",
  "At least one active project owner is required.": "有効な所有者を最低1人残す必要があります。",
  "Project membership already exists.": "このメンバーはすでに登録されています。",
  "Project membership role is invalid.": "メンバー権限が不正です。",
  "Project membership is not active.": "このメンバーは有効ではありません。",
  "Failed job discard confirmation is required.": "失敗ジョブを破棄する前にリスク確認が必要です。",
  "Validation failed": "入力内容の検証に失敗しました。",
};

const statusLabels: Record<string, string> = {
  accepted_risk: "リスク承認済み",
  action_required: "対応が必要",
  active: "有効",
  admin: "管理者",
  approved: "承認済み",
  archived: "アーカイブ済み",
  auditor: "監査担当",
  block: "停止",
  blocked: "ブロック中",
  cancelled: "キャンセル済み",
  clear: "通過",
  connected: "接続済み",
  draft: "下書き",
  editor: "編集者",
  error: "エラー",
  failed: "失敗",
  generated: "生成済み",
  generating: "生成中",
  github_created: "GitHub作成済み",
  degraded: "要確認",
  healthy: "正常",
  in_review: "レビュー中",
  invalid: "検証失敗",
  local_saved: "ローカル保存済み",
  manually_reconciled: "手動照合済み",
  needs_changes: "修正が必要",
  needs_revision: "修正が必要",
  not_connected: "未接続",
  not_evaluated: "未評価",
  not_measured: "未計測",
  open: "未対応",
  owner: "所有者",
  pass: "通過",
  pending: "未対応",
  product_job_ambiguous: "管理ジョブ候補が複数",
  product_job_lookup_failed: "管理ジョブ確認失敗",
  product_job_unresolved: "管理ジョブ未確認",
  project_mismatch: "Project不一致",
  publish_failed: "GitHub公開失敗",
  published: "公開済み",
  publishing: "公開中",
  ready_for_ai: "AI整理可能",
  redaction_required: "マスキングが必要",
  reconciled: "照合済み",
  reconciliation_required: "GitHub Issueの照合が必要",
  rejected: "却下済み",
  resolved: "解決済み",
  review_required: "レビューが必要",
  reviewer: "レビュー担当",
  retry_approved: "再試行承認済み",
  revoked: "失効済み",
  running: "実行中",
  saved: "保存済み",
  solid_queue_job_missing: "Queue job未確認",
  started: "開始済み",
  stale: "再確認が必要",
  summarizing: "整理中",
  summary_draft: "整理ドラフトあり",
  succeeded: "完了",
  unavailable: "利用不可",
  valid: "検証済み",
  verified: "確認済み",
  viewer: "閲覧者",
  warning: "警告",
};

const targetLabels: Record<string, string> = {
  issue_draft: "Issueドラフト",
  conversation_summary_draft: "DM整理ドラフト",
  minutes: "議事録",
  openapi_draft: "OpenAPIドラフト",
  requirement: "要件定義",
};

export function displayMessage(message?: string) {
  if (!message) return "";
  return messageLabels[message] ?? message;
}

export function statusLabel(status?: string, fallback = "未生成") {
  if (!status) return fallback;
  return statusLabels[status] ?? status;
}

export function targetLabel(target?: string) {
  if (!target) return "-";
  return targetLabels[target] ?? target;
}

export function yesNoLabel(value: boolean) {
  return value ? "はい" : "いいえ";
}
